// src/pages/TaskDetail/index.tsx
﻿import { useMemo, useState, useEffect } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import {
  Descriptions,
  Button,
  Card,
  Typography,
  Space,
  Empty,
  Upload,
  Modal,
  Alert,
  Table,
  message,
  Popconfirm,
  Tag,
  DatePicker,
  Form,
  InputNumber,
} from 'antd';
import {
  ArrowLeftOutlined,
  EditOutlined,
  ImportOutlined,
  InboxOutlined,
  FileTextOutlined,
  UndoOutlined,
  RocketOutlined,
  FieldTimeOutlined,
} from '@ant-design/icons';
import dayjs, { type Dayjs } from 'dayjs';

import { useTaskStore } from '../../store/useTaskStore';
import { useAnnotationStore } from '../../store/useAnnotationStore';
import { useAuthStore } from '../../store/useAuthStore';
import { batchImportItems } from '../../api/annotation';
import { renderStatusTag, renderTaskTypeTag, canEdit } from '../TaskList/constants';
import TaskAssignmentPanel from './TaskAssignmentPanel';
import { Role, TaskStatus } from '../../types';
import { formatTaskTimeRange, getTaskTimeliness } from '../../utils/taskTimeliness';

const { Title, Text } = Typography;
const { Dragger } = Upload;

interface TimeLimitFormValues {
  startsAt?: Dayjs | null;
  dueAt?: Dayjs | null;
  annotationTimeoutHours?: number;
  reviewTimeoutHours?: number;
}

export default function TaskDetail() {
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const taskId = searchParams.get('id');

  const user = useAuthStore((s) => s.user);
  const tasks = useTaskStore((s) => s.tasks);
  const archivedTasks = useTaskStore((s) => s.archivedTasks);
  const fetchTasks = useTaskStore((s) => s.fetchTasks);
  const fetchArchivedTasks = useTaskStore((s) => s.fetchArchivedTasks);
  const archiveTask = useTaskStore((s) => s.archiveTask);
  const unarchiveTask = useTaskStore((s) => s.unarchiveTask);
  const updateTask = useTaskStore((s) => s.updateTask);
  const fetchDataItems = useAnnotationStore((s) => s.fetchDataItems);
  const isOwner = user?.role === Role.OWNER;
  const task = useMemo(
    () => (taskId ? tasks.find((t) => t.id === taskId) || archivedTasks.find((t) => t.id === taskId) : undefined),
    [taskId, tasks, archivedTasks],
  );
  const isArchived = useMemo(() => (taskId ? archivedTasks.some((t) => t.id === taskId) : false), [taskId, archivedTasks]);

  // 确保归档任务也已加载（以便通过 URL 直接访问归档任务详情）
  useEffect(() => {
    fetchTasks();
    fetchArchivedTasks();
  }, [fetchArchivedTasks, fetchTasks]);

  // 导入相关状态
  const [importModalOpen, setImportModalOpen] = useState(false);
  const [timeLimitModalOpen, setTimeLimitModalOpen] = useState(false);
  const [timeLimitSaving, setTimeLimitSaving] = useState(false);
  const [timeLimitForm] = Form.useForm<TimeLimitFormValues>();
  const [importLoading, setImportLoading] = useState(false);
  const [previewData, setPreviewData] = useState<Array<{ rawData: Record<string, unknown> }>>([]);

  /** 解析上传的 JSON 文件 */
  const parseJsonFile = (file: File) => {
    const reader = new FileReader();
    reader.onload = (e) => {
      try {
        const content = JSON.parse(e.target?.result as string);
        // 支持两种格式：数组 或 { items: [...] }
        const items: unknown[] = Array.isArray(content) ? content : content?.items;
        if (!Array.isArray(items) || items.length === 0) {
          message.error('JSON 文件格式错误：需要数组或 { items: [...] } 格式');
          return;
        }
        // 每个元素包装为 { rawData: ... }
        const wrapped = items.map((item) => ({
          rawData: typeof item === 'object' && item !== null ? item as Record<string, unknown> : { value: item },
        }));
        setPreviewData(wrapped);
        message.success(`已解析 ${wrapped.length} 条数据`);
      } catch {
        message.error('JSON 解析失败，请检查文件格式');
      }
    };
    reader.readAsText(file);
    return false; // 阻止自动上传
  };

  /** 执行导入 */
  const handleImport = async () => {
    if (!taskId || previewData.length === 0) return;
    setImportLoading(true);
    try {
      const res = await batchImportItems(taskId, previewData);
      message.success(`成功导入 ${res.data.imported} 条数据`);
      setImportModalOpen(false);
      setPreviewData([]);
      // 刷新数据
      fetchDataItems(taskId);
      fetchTasks();
    } catch (err: any) {
      message.error(err?.message || '导入失败');
    } finally {
      setImportLoading(false);
    }
  };

  if (!task) {
    return (
      <>
        <Button
          icon={<ArrowLeftOutlined />}
          onClick={() => navigate(isArchived ? '/archive' : '/tasks')}
          style={{ marginBottom: 16 }}
        >
          返回
        </Button>
        <Empty description="未找到该任务" />
      </>
    );
  }

  const isEditable = canEdit(task.status);
  const timeliness = getTaskTimeliness(task);

  const openTimeLimitModal = () => {
    timeLimitForm.setFieldsValue({
      startsAt: task.startsAt ? dayjs(task.startsAt) : null,
      dueAt: task.dueAt ? dayjs(task.dueAt) : null,
      annotationTimeoutHours: task.annotationTimeoutHours ?? task.reminderHours ?? 24,
      reviewTimeoutHours: task.reviewTimeoutHours ?? task.reviewReminderHours ?? 24,
    });
    setTimeLimitModalOpen(true);
  };

  const handleSaveTimeLimit = async () => {
    const values = await timeLimitForm.validateFields();
    setTimeLimitSaving(true);
    try {
      await updateTask(task.id, {
        startsAt: values.startsAt ? values.startsAt.toISOString() : null,
        dueAt: values.dueAt ? values.dueAt.toISOString() : null,
        annotationTimeoutHours: values.annotationTimeoutHours ?? 24,
        reviewTimeoutHours: values.reviewTimeoutHours ?? 24,
      });
      message.success('任务时限已更新');
      setTimeLimitModalOpen(false);
      fetchTasks();
    } catch (err: any) {
      message.error(err?.message || '更新时限失败');
    } finally {
      setTimeLimitSaving(false);
    }
  };

  const previewColumns = [
    {
      title: '序号',
      key: 'index',
      width: 60,
      render: (_: unknown, __: unknown, index: number) => index + 1,
    },
    {
      title: 'rawData 摘要',
      dataIndex: 'rawData',
      key: 'rawData',
      ellipsis: true,
      render: (v: Record<string, unknown>) => JSON.stringify(v).slice(0, 100) + '…',
    },
  ];

  return (
    <>
      <Title level={4}>任务详情</Title>

      <Card>
        <Descriptions column={2} bordered size="middle">
          <Descriptions.Item label="任务名称">{task.name}</Descriptions.Item>
          <Descriptions.Item label="任务类型">
            {renderTaskTypeTag(task.type)}
          </Descriptions.Item>
          <Descriptions.Item label="负责人">{task.owner}</Descriptions.Item>
          <Descriptions.Item label="状态">
            {renderStatusTag(task.status)}
          </Descriptions.Item>
          <Descriptions.Item label="绑定模板">{task.templateName}</Descriptions.Item>
          <Descriptions.Item label="创建时间">
            {dayjs(task.createdAt).format('YYYY-MM-DD HH:mm')}
          </Descriptions.Item>
          <Descriptions.Item label="任务时效">
            <Space direction="vertical" size={4}>
              <Tag color={timeliness.color}>{timeliness.label}</Tag>
              <Text type="secondary">{timeliness.description}</Text>
            </Space>
          </Descriptions.Item>
          <Descriptions.Item label="任务时间窗口">
            {formatTaskTimeRange(task)}
          </Descriptions.Item>
          <Descriptions.Item label="标注项时限">
            领取或分配后 {task.annotationTimeoutHours ?? task.reminderHours ?? 24} 小时
          </Descriptions.Item>
          <Descriptions.Item label="审核项时限">
            领取或分配后 {task.reviewTimeoutHours ?? task.reviewReminderHours ?? 24} 小时
          </Descriptions.Item>
          {isArchived && (
            <>
              <Descriptions.Item label="归档时间">
                {task.archivedAt ? dayjs(task.archivedAt).format('YYYY-MM-DD HH:mm') : '—'}
              </Descriptions.Item>
              <Descriptions.Item label="归档状态">
                <Tag color="default">已归档</Tag>
              </Descriptions.Item>
            </>
          )}
          <Descriptions.Item label="任务描述" span={2}>
            {task.description || '—'}
          </Descriptions.Item>
          <Descriptions.Item label="任务说明" span={2}>
            <div style={{ whiteSpace: 'pre-wrap' }}>
              {task.instructions || '—'}
            </div>
          </Descriptions.Item>
        </Descriptions>

        {(timeliness.level === 'due_soon' || timeliness.level === 'overdue') && !isArchived && (
          <Alert
            type={timeliness.level === 'overdue' ? 'error' : 'warning'}
            showIcon
            message={timeliness.label}
            description={timeliness.description}
            style={{ marginTop: 16 }}
          />
        )}

        <Space style={{ marginTop: 24 }}>
          <Button icon={<ArrowLeftOutlined />} onClick={() => navigate(isArchived ? '/archive' : '/tasks')}>
            {isArchived ? '返回归档' : '返回列表'}
          </Button>
          {isEditable && !isArchived && (
            <Button
              type="primary"
              icon={<EditOutlined />}
              onClick={() => navigate(`/tasks/edit?id=${task.id}`)}
            >
              编辑任务
            </Button>
          )}
          {!isArchived && (
            <Button
              icon={<ImportOutlined />}
              onClick={() => setImportModalOpen(true)}
            >
              导入数据
            </Button>
          )}
          {isOwner && !isArchived && (
            <Button icon={<FieldTimeOutlined />} onClick={openTimeLimitModal}>
              调整时限
            </Button>
          )}
          {isOwner && !isArchived && (task.status === 'completed' || task.status === 'ended') && (
            <Popconfirm
              title="确认归档该任务？归档后可到「任务归档」中查看。"
              onConfirm={async () => {
                await archiveTask(task.id);
                message.success('任务已归档');
                navigate('/archive');
              }}
            >
              <Button icon={<InboxOutlined />}>归档</Button>
            </Popconfirm>
          )}
          {isOwner && isArchived && (
            <Popconfirm
              title="确认取消归档？任务将恢复到任务列表。"
              onConfirm={async () => {
                await unarchiveTask(task.id);
                message.success('已取消归档');
                navigate('/archive');
              }}
            >
              <Button icon={<UndoOutlined />}>取消归档</Button>
            </Popconfirm>
          )}
        </Space>
      </Card>

      {/* 任务分配面板 - 仅 Owner 可见，归档任务不显示 */}
      {taskId && isOwner && !isArchived && task.status === 'in_progress' && (
        <TaskAssignmentPanel
          taskId={taskId}
          onAssignmentChange={() => fetchDataItems(taskId)}
        />
      )}

      {/* 未发布任务提示 - 引导 Owner 先发布任务 */}
      {taskId && isOwner && !isArchived && (task.status === 'draft' || task.status === 'pending') && (
        <Card style={{ marginTop: 16 }}>
          <Alert
            type="warning"
            showIcon
            icon={<RocketOutlined />}
            message="任务尚未发布"
            description={
              <div>
                <p style={{ marginBottom: 8 }}>任务必须先发布后才能进行分配、标注和审核操作。未发布的任务不会对标注员和审核员可见。</p>
                <Button
                  type="primary"
                  icon={<RocketOutlined />}
                  onClick={async () => {
                    try {
                      await updateTask(task.id, { status: TaskStatus.IN_PROGRESS });
                      message.success('任务已发布，现在可以进行分配了');
                      fetchTasks();
                    } catch (err: any) {
                      message.error(err?.message || '发布失败');
                    }
                  }}
                >
                  立即发布任务
                </Button>
              </div>
            }
          />
        </Card>
      )}

      {/* 数据导入弹窗 */}
      <Modal
        title="导入标注数据"
        open={importModalOpen}
        onCancel={() => {
          setImportModalOpen(false);
          setPreviewData([]);
        }}
        onOk={handleImport}
        okText={`确认导入（${previewData.length} 条）`}
        okButtonProps={{ disabled: previewData.length === 0 }}
        confirmLoading={importLoading}
        width={720}
      >
        <Alert
          type="info"
          showIcon
          style={{ marginBottom: 16 }}
          message="数据格式说明"
          description={
            <div>
              <p style={{ marginBottom: 4 }}>请上传 JSON 文件，支持以下格式：</p>
              <Text code>{'[ {"text": "示例1"}, {"text": "示例2"} ]'}</Text>
              <br />
              <Text code>{'{ "items": [ {"text": "示例1"}, {"text": "示例2"} ] }'}</Text>
              <p style={{ marginTop: 8, marginBottom: 0 }}>
                每个元素将作为一条待标注数据的 rawData 字段存储。
              </p>
            </div>
          }
        />

        <Dragger
          accept=".json"
          maxCount={1}
          showUploadList={false}
          beforeUpload={parseJsonFile}
        >
          <p className="ant-upload-drag-icon">
            <InboxOutlined />
          </p>
          <p className="ant-upload-text">点击或拖拽 JSON 文件到此处</p>
          <p className="ant-upload-hint">支持 .json 格式</p>
        </Dragger>

        {previewData.length > 0 && (
          <div style={{ marginTop: 16 }}>
            <Text strong>
              <FileTextOutlined style={{ marginRight: 4 }} />
              数据预览（共 {previewData.length} 条）
            </Text>
            <Table
              size="small"
              columns={previewColumns}
              dataSource={previewData}
              pagination={{ pageSize: 5, showTotal: (total) => `共 ${total} 条` }}
              rowKey={(_, index) => String(index)}
              style={{ marginTop: 8 }}
            />
          </div>
        )}
      </Modal>

      <Modal
        title="调整任务时限"
        open={timeLimitModalOpen}
        onCancel={() => setTimeLimitModalOpen(false)}
        onOk={handleSaveTimeLimit}
        confirmLoading={timeLimitSaving}
        width={760}
        okText="保存时限"
      >
        <Form form={timeLimitForm} layout="vertical">
          <Card size="small" title="任务周期与单项时限">
            <Space wrap align="start">
              <Form.Item name="startsAt" label="任务开始">
                <DatePicker showTime style={{ width: 220 }} placeholder="立即开始" />
              </Form.Item>
              <Form.Item
                name="dueAt"
                label="任务期限"
                dependencies={['startsAt']}
                rules={[
                  ({ getFieldValue }) => ({
                    validator(_, value: Dayjs | null) {
                      const startsAt = getFieldValue('startsAt') as Dayjs | null;
                      if (!value || !startsAt || value.isAfter(startsAt)) return Promise.resolve();
                      return Promise.reject(new Error('任务期限必须晚于任务开始'));
                    },
                  }),
                ]}
              >
                <DatePicker showTime style={{ width: 220 }} placeholder="选择任务期限" />
              </Form.Item>
              <Form.Item name="annotationTimeoutHours" label="标注项时限">
                <InputNumber min={0} max={720} addonAfter="小时" style={{ width: 160 }} />
              </Form.Item>
              <Form.Item name="reviewTimeoutHours" label="审核项时限">
                <InputNumber min={0} max={720} addonAfter="小时" style={{ width: 160 }} />
              </Form.Item>
            </Space>
          </Card>
        </Form>
      </Modal>
    </>
  );
}

// src/pages/TaskDetail/index.vue
<template>
  <section class="task-detail-page app-page">
    <header class="app-page-header">
      <div class="app-page-title">
        <a-typography-title :level="4" class="page-title">任务详情</a-typography-title>
        <a-typography-text class="app-page-desc" type="secondary">
          查看任务配置、数据明细与分配进度。
        </a-typography-text>
      </div>
    </header>

    <a-empty v-if="!task" description="未找到该任务">
      <a-button @click="router.push('/tasks')">返回列表</a-button>
    </a-empty>

    <template v-else>
      <a-card>
        <a-descriptions bordered :column="2">
          <a-descriptions-item label="任务名称">{{ task.name }}</a-descriptions-item>
          <a-descriptions-item label="任务类型">
            <a-tag :color="getTaskTypeMeta(task.type).color">
              {{ getTaskTypeMeta(task.type).label }}
            </a-tag>
          </a-descriptions-item>
          <a-descriptions-item label="负责人">{{ task.owner }}</a-descriptions-item>
          <a-descriptions-item label="状态">
            <a-tag :color="getTaskStatusMeta(task.status).color">
              {{ getTaskStatusMeta(task.status).label }}
            </a-tag>
          </a-descriptions-item>
          <a-descriptions-item label="绑定模板">{{ task.templateName }}</a-descriptions-item>
          <a-descriptions-item label="创建时间">
            {{ formatDate(task.createdAt) }}
          </a-descriptions-item>
          <a-descriptions-item label="任务时间窗口">
            {{ formatRange(task.startsAt, task.dueAt) }}
          </a-descriptions-item>
          <a-descriptions-item label="单项时限">
            标注 {{ task.annotationTimeoutHours ?? 24 }} 小时 / 审核
            {{ task.reviewTimeoutHours ?? 24 }} 小时
          </a-descriptions-item>
          <a-descriptions-item label="任务描述" :span="2">
            {{ task.description || '-' }}
          </a-descriptions-item>
          <a-descriptions-item label="任务说明" :span="2">
            <div class="pre-wrap">{{ task.instructions || '-' }}</div>
          </a-descriptions-item>
        </a-descriptions>

        <a-space class="actions" wrap>
          <a-button @click="router.push(isArchived ? '/archive' : '/tasks')">
            <template #icon><ArrowLeftOutlined /></template>
            {{ isArchived ? '返回归档' : '返回列表' }}
          </a-button>
          <a-button
            v-if="canEditTask"
            type="primary"
            @click="router.push(`/tasks/edit?id=${task.id}`)"
          >
            <template #icon><EditOutlined /></template>
            编辑任务
          </a-button>
          <a-button v-if="!isArchived" @click="importOpen = true">
            <template #icon><ImportOutlined /></template>
            导入数据
          </a-button>
          <a-button v-if="canPublishTask" type="primary" @click="publishTask">
            <template #icon><RocketOutlined /></template>
            发布任务
          </a-button>
          <a-popconfirm
            v-if="canArchiveTask"
            title="确认归档该任务？"
            @confirm="archiveCurrentTask"
          >
            <a-button>
              <template #icon><InboxOutlined /></template>
              归档
            </a-button>
          </a-popconfirm>
          <a-popconfirm
            v-if="isArchived && isManager"
            title="确认取消归档？"
            @confirm="unarchiveCurrentTask"
          >
            <a-button>
              <template #icon><UndoOutlined /></template>
              取消归档
            </a-button>
          </a-popconfirm>
        </a-space>
      </a-card>

      <a-card size="small" :body-style="{ padding: '0 16px 16px' }">
        <a-tabs v-model:active-key="activeTab">
          <a-tab-pane key="data" tab="数据概览">
            <a-table
              row-key="id"
              size="small"
              :columns="itemColumns"
              :data-source="annotationStore.dataItems"
              :loading="annotationStore.loading"
              :pagination="{ pageSize: 10, showSizeChanger: false }"
            >
              <template #bodyCell="{ column, record }">
                <template v-if="column.key === 'status'">
                  <a-tag :color="getDataStatusMeta(record.status).color">
                    {{ getDataStatusMeta(record.status).label }}
                  </a-tag>
                </template>
                <template v-else-if="column.key === 'rawData'">
                  <a-tooltip :title="stringify(record.rawData)">
                    <span class="ellipsis-text">{{ stringify(record.rawData) }}</span>
                  </a-tooltip>
                </template>
                <template v-else-if="column.key === 'submittedAt'">
                  {{ formatDate(record.submittedAt) }}
                </template>
              </template>
            </a-table>
          </a-tab-pane>

          <a-tab-pane v-if="isManager" key="assign" tab="标注分配">
            <AnnotationAssignmentPanel :task-id="taskId" />
          </a-tab-pane>

          <a-tab-pane v-if="isManager" key="review-assign" tab="审核分配">
            <ReviewAssignmentPanel :task-id="taskId" />
          </a-tab-pane>
        </a-tabs>
      </a-card>
    </template>

    <a-modal
      v-model:open="importOpen"
      title="导入标注数据"
      width="720px"
      :ok-text="`确认导入（${previewData.length} 条）`"
      :ok-button-props="{ disabled: previewData.length === 0 }"
      :confirm-loading="importLoading"
      @ok="handleImport"
      @cancel="previewData = []"
    >
      <div class="lh-modal-stack">
        <a-alert
          type="info"
          show-icon
          message="请上传 JSON 文件，支持数组或 { items: [...] } 格式。每个元素会作为 rawData 导入。"
          class="import-alert"
        />
        <input type="file" accept=".json,application/json" @change="handleFileChange" />

        <a-table
          v-if="previewData.length > 0"
          row-key="key"
          size="small"
          class="preview-table lh-modal-table"
          :columns="previewColumns"
          :data-source="previewRows"
          :pagination="{ pageSize: 5, showSizeChanger: false }"
        />
      </div>
    </a-modal>
  </section>
</template>

<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { message, type TableColumnsType } from 'ant-design-vue';
import {
  ArrowLeftOutlined,
  EditOutlined,
  ImportOutlined,
  InboxOutlined,
  RocketOutlined,
  UndoOutlined,
} from '@ant-design/icons-vue';
import { batchImportItems } from '../../api/annotation';
import { Role, TaskStatus, type DataItem } from '../../types';
import { getDataStatusMeta, getTaskStatusMeta, getTaskTypeMeta } from '../../utils/statusMeta';
import { useAnnotationStore } from '../../store/useAnnotationStore';
import { useAuthStore } from '../../store/useAuthStore';
import { useTaskStore } from '../../store/useTaskStore';
import AnnotationAssignmentPanel from './components/AnnotationAssignmentPanel.vue';
import ReviewAssignmentPanel from './components/ReviewAssignmentPanel.vue';

const route = useRoute();
const router = useRouter();
const authStore = useAuthStore();
const taskStore = useTaskStore();
const annotationStore = useAnnotationStore();

const importOpen = ref(false);
const importLoading = ref(false);
const previewData = ref<Array<{ rawData: Record<string, unknown> }>>([]);
const activeTab = ref('data');

const taskId = computed(() => (typeof route.query.id === 'string' ? route.query.id : ''));
const task = computed(
  () =>
    taskStore.tasks.find((item) => item.id === taskId.value) ??
    taskStore.archivedTasks.find((item) => item.id === taskId.value),
);
const isArchived = computed(() => taskStore.archivedTasks.some((item) => item.id === taskId.value));
const isManager = computed(
  () => authStore.user?.role === Role.ADMIN || authStore.user?.role === Role.OWNER,
);
const canEditTask = computed(() =>
  Boolean(
    task.value &&
    !isArchived.value &&
    [TaskStatus.DRAFT, TaskStatus.PENDING].includes(task.value.status),
  ),
);
const canPublishTask = computed(() =>
  Boolean(
    task.value &&
    !isArchived.value &&
    [TaskStatus.DRAFT, TaskStatus.PENDING].includes(task.value.status),
  ),
);
const canArchiveTask = computed(() =>
  Boolean(
    task.value &&
    isManager.value &&
    !isArchived.value &&
    [TaskStatus.COMPLETED, TaskStatus.ENDED].includes(task.value.status),
  ),
);

const itemColumns: TableColumnsType<DataItem> = [
  { title: 'ID', dataIndex: 'id', key: 'id', width: 120, ellipsis: true },
  { title: '状态', dataIndex: 'status', key: 'status', width: 104 },
  { title: '标注员', dataIndex: 'annotator', key: 'annotator', width: 104, responsive: ['md'] },
  { title: '审核员', dataIndex: 'reviewer', key: 'reviewer', width: 104, responsive: ['xl'] },
  { title: '原始数据', dataIndex: 'rawData', key: 'rawData', ellipsis: true },
  {
    title: '提交时间',
    dataIndex: 'submittedAt',
    key: 'submittedAt',
    width: 148,
    responsive: ['lg'],
  },
];

const previewColumns = [
  { title: '序号', dataIndex: 'key', key: 'key', width: 80 },
  { title: 'rawData 摘要', dataIndex: 'summary', key: 'summary', ellipsis: true },
];

const previewRows = computed(() =>
  previewData.value.map((item, index) => ({
    key: index + 1,
    summary: stringify(item.rawData),
  })),
);

onMounted(() => {
  void taskStore.fetchTasks();
  void taskStore.fetchArchivedTasks();
  loadItems();
});

watch(taskId, () => loadItems());

function loadItems() {
  if (taskId.value) void annotationStore.fetchDataItems(taskId.value);
}

async function publishTask() {
  if (!task.value) return;
  await taskStore.updateTask(task.value.id, { status: TaskStatus.IN_PROGRESS });
  message.success('任务已发布');
}

async function archiveCurrentTask() {
  if (!task.value) return;
  await taskStore.archiveTask(task.value.id);
  message.success('任务已归档');
  await router.push('/archive');
}

async function unarchiveCurrentTask() {
  if (!task.value) return;
  await taskStore.unarchiveTask(task.value.id);
  message.success('已取消归档');
  await router.push('/archive');
}

function handleFileChange(event: Event) {
  const input = event.target as HTMLInputElement;
  const file = input.files?.[0];
  if (!file) return;
  const reader = new FileReader();
  reader.onload = () => {
    try {
      const parsed = JSON.parse(String(reader.result ?? ''));
      const items: unknown[] = Array.isArray(parsed) ? parsed : parsed?.items;
      if (!Array.isArray(items) || items.length === 0) {
        message.error('JSON 文件格式错误：需要数组或 { items: [...] } 格式');
        return;
      }
      previewData.value = items.map((item) => ({
        rawData:
          item && typeof item === 'object' ? (item as Record<string, unknown>) : { value: item },
      }));
      message.success(`已解析 ${previewData.value.length} 条数据`);
    } catch {
      message.error('JSON 解析失败，请检查文件格式');
    }
  };
  reader.readAsText(file);
}

async function handleImport() {
  if (!taskId.value || previewData.value.length === 0) return;
  importLoading.value = true;
  try {
    const res = await batchImportItems(taskId.value, previewData.value);
    message.success(`成功导入 ${res.data.imported} 条数据`);
    importOpen.value = false;
    previewData.value = [];
    loadItems();
  } catch (error) {
    message.error(error instanceof Error ? error.message : '导入失败');
  } finally {
    importLoading.value = false;
  }
}

function formatDate(value: string | null) {
  return value ? new Date(value).toLocaleString('zh-CN', { hour12: false }) : '-';
}

function formatRange(start: string | null, end: string | null) {
  return `${formatDate(start)} - ${formatDate(end)}`;
}

function stringify(value: unknown) {
  return value === null || value === undefined ? '-' : JSON.stringify(value);
}
</script>

<style scoped>
.page-title {
  margin: 0;
}

.actions {
  margin-top: 24px;
}

.pre-wrap {
  white-space: pre-wrap;
}

.ellipsis-text {
  display: inline-block;
  max-width: 360px;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  vertical-align: bottom;
}

.import-alert,
.preview-table {
  margin-top: 16px;
}
</style>
