// src/pages/TaskForm/index.tsx
﻿import { useEffect, useMemo, useState } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import {
  Form,
  Input,
  Select,
  DatePicker,
  InputNumber,
  Button,
  Card,
  Space,
  Typography,
  message,
  Spin,
  Alert,
} from 'antd';
import { ArrowLeftOutlined } from '@ant-design/icons';
import dayjs, { type Dayjs } from 'dayjs';
import { TaskStatus, AssignmentStrategy, type TaskItem } from '../../types';
import { useTaskStore } from '../../store/useTaskStore';
import { useTemplateStore } from '../../store/useTemplateStore';
import { getUserList } from '../../api/template';
import { taskTypeMap } from '../TaskList/constants';
const { Title } = Typography;
const { TextArea } = Input;

/** 任务类型下拉选项 */
const taskTypeOptions = Object.entries(taskTypeMap).map(([value, { label }]) => ({
  label,
  value,
}));

interface UserOption {
  label: string;
  value: string;
}

interface TaskFormValues {
  name: string;
  description: string;
  type: TaskItem['type'];
  owner: string;
  templateId: string;
  instructions: string;
  startsAt?: Dayjs | null;
  dueAt?: Dayjs | null;
  annotationTimeoutHours?: number;
  reviewTimeoutHours?: number;
}

export default function TaskForm() {
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const editId = searchParams.get('id');

  const tasks = useTaskStore((s) => s.tasks);
  const taskLoading = useTaskStore((s) => s.loading);
  const taskError = useTaskStore((s) => s.error);
  const addTask = useTaskStore((s) => s.addTask);
  const updateTask = useTaskStore((s) => s.updateTask);

  const templates = useTemplateStore((s) => s.templates);
  const tplLoading = useTemplateStore((s) => s.loading);
  const fetchTemplates = useTemplateStore((s) => s.fetchTemplates);

  const [ownerOptions, setOwnerOptions] = useState<UserOption[]>([]);
  const [optionsLoading, setOptionsLoading] = useState(false);
  const [optionsError, setOptionsError] = useState<string | null>(null);

  const [form] = Form.useForm();

  const isEdit = Boolean(editId);
  const editingTask = useMemo(
    () => (editId ? tasks.find((t) => t.id === editId) : undefined),
    [editId, tasks],
  );

  // 加载模板列表和用户列表
  useEffect(() => {
    const loadOptions = async () => {
      setOptionsLoading(true);
      setOptionsError(null);
      try {
        const [, userRes] = await Promise.all([
          fetchTemplates(),
          getUserList(),
        ]);
        const owners = (userRes.data.items || [])
          .filter((u) => u.role === 'owner')
          .map((u) => ({ label: u.username, value: u.username }));
        setOwnerOptions(owners);
      } catch (err: any) {
        setOptionsError(err?.message || '加载选项失败');
      } finally {
        setOptionsLoading(false);
      }
    };
    loadOptions();
  }, [fetchTemplates]);

  // 编辑模式时填充表单
  useEffect(() => {
    if (editingTask) {
      form.setFieldsValue({
        name: editingTask.name,
        description: editingTask.description,
        type: editingTask.type,
        owner: editingTask.owner,
        templateId: editingTask.templateId,
        instructions: editingTask.instructions,
        startsAt: editingTask.startsAt ? dayjs(editingTask.startsAt) : null,
        dueAt: editingTask.dueAt ? dayjs(editingTask.dueAt) : null,
        annotationTimeoutHours: editingTask.annotationTimeoutHours ?? editingTask.reminderHours ?? 24,
        reviewTimeoutHours: editingTask.reviewTimeoutHours ?? editingTask.reviewReminderHours ?? 24,
      });
    }
  }, [editingTask, form]);

  const handleTypeChange = () => {
    form.setFieldValue('templateId', undefined);
  };

  const selectedType = Form.useWatch('type', form);
  const templateOptions = useMemo(() => {
    const all = selectedType
      ? templates.filter((t) => t.type === selectedType)
      : templates;
    return all.map((t) => ({ label: t.name, value: t.id }));
  }, [selectedType, templates]);

  const handleSubmit = async () => {
    const values = await form.validateFields() as TaskFormValues;
    const timeFields = {
      startsAt: values.startsAt ? values.startsAt.toISOString() : null,
      dueAt: values.dueAt ? values.dueAt.toISOString() : null,
      annotationTimeoutHours: values.annotationTimeoutHours ?? 24,
      reviewTimeoutHours: values.reviewTimeoutHours ?? 24,
    };

    if (isEdit && editId) {
      const selectedTemplate = templates.find((t) => t.id === values.templateId);
      try {
        await updateTask(editId, {
          ...values,
          ...timeFields,
          templateName: selectedTemplate?.name ?? '',
        });
        message.success('任务已更新');
        navigate('/tasks');
      } catch {
        // updateTask already sets error state, don't navigate
      }
    } else {
      const selectedTemplate = templates.find((t) => t.id === values.templateId);
      // Don't send id — let the backend generate a unique one
      const newTask: Partial<TaskItem> = {
        name: values.name,
        description: values.description ?? '',
        type: values.type,
        owner: values.owner,
        templateId: values.templateId,
        templateName: selectedTemplate?.name ?? '',
        instructions: values.instructions ?? '',
        ...timeFields,
        status: TaskStatus.DRAFT,
        assignmentConfig: {
          strategy: AssignmentStrategy.EVEN_SPLIT,
          annotators: [],
          options: {},
        },
        archived: false,
        archivedAt: null,
      };
      try {
        await addTask(newTask as TaskItem);
        message.success('任务创建成功');
        navigate('/tasks');
      } catch {
        // addTask already sets error state, don't navigate
      }
    }
  };

  const isLoading = taskLoading || tplLoading || optionsLoading;

  return (
    <>
      <Title level={4}>{isEdit ? '编辑任务' : '创建任务'}</Title>

      {(taskError || optionsError) && (
        <Alert
          type="error"
          message={taskError || optionsError || ''}
          showIcon
          closable
          style={{ marginBottom: 16 }}
        />
      )}

      <Spin spinning={isLoading}>
        <Card style={{ maxWidth: 720 }}>
          <Form
            form={form}
            layout="vertical"
            autoComplete="off"
            onFinish={handleSubmit}
          >
            <Form.Item
              name="name"
              label="任务名称"
              rules={[
                { required: true, message: '请输入任务名称' },
                { max: 50, message: '任务名称不能超过50个字符' },
              ]}
            >
              <Input placeholder="请输入任务名称" maxLength={50} showCount />
            </Form.Item>

            <Form.Item
              name="description"
              label="任务描述"
              rules={[
                { required: true, message: '请输入任务描述' },
                { max: 200, message: '任务描述不能超过200个字符' },
              ]}
            >
              <TextArea
                placeholder="请输入任务描述"
                maxLength={200}
                showCount
                rows={3}
              />
            </Form.Item>

            <Form.Item
              name="type"
              label="任务类型"
              rules={[{ required: true, message: '请选择任务类型' }]}
            >
              <Select
                placeholder="请选择任务类型"
                options={taskTypeOptions}
                onChange={handleTypeChange}
              />
            </Form.Item>

            <Form.Item
              name="owner"
              label="负责人"
              rules={[{ required: true, message: '请选择负责人' }]}
            >
              <Select placeholder="请选择负责人" options={ownerOptions} loading={optionsLoading} />
            </Form.Item>

            <Form.Item
              name="templateId"
              label="绑定模板"
              rules={[{ required: true, message: '请选择绑定模板' }]}
            >
              <Select
                placeholder={selectedType ? '请选择模板' : '请先选择任务类型'}
                options={templateOptions}
                disabled={!selectedType}
                loading={tplLoading}
              />
            </Form.Item>

            <Form.Item
              name="instructions"
              label="任务说明"
              rules={[
                { required: true, message: '请输入任务说明' },
                { max: 500, message: '任务说明不能超过500个字符' },
              ]}
            >
              <TextArea
                placeholder="请输入任务说明，如标注规范、注意事项等"
                maxLength={500}
                showCount
                rows={4}
              />
            </Form.Item>

            <Card size="small" title="任务时效" style={{ marginBottom: 24 }}>
              <Space direction="vertical" style={{ width: '100%' }} size={12}>
                <Space wrap align="start">
                  <Form.Item
                    name="startsAt"
                    label="任务开始"
                    style={{ marginBottom: 0 }}
                  >
                    <DatePicker showTime style={{ width: 220 }} placeholder="立即开始" />
                  </Form.Item>

                  <Form.Item
                    name="dueAt"
                    label="任务期限"
                    dependencies={['startsAt']}
                    rules={[
                      ({ getFieldValue }) => ({
                        validator(_, value: Dayjs | null) {
                          const startsAt = getFieldValue('startsAt') as Dayjs | null;
                          if (!value || !startsAt || value.isAfter(startsAt)) {
                            return Promise.resolve();
                          }
                          return Promise.reject(new Error('任务期限必须晚于任务开始'));
                        },
                      }),
                    ]}
                    style={{ marginBottom: 0 }}
                  >
                    <DatePicker showTime style={{ width: 220 }} placeholder="选择截止时间" />
                  </Form.Item>
                </Space>

                <Space wrap align="start">
                  <Form.Item
                    name="annotationTimeoutHours"
                    label="标注项时限"
                    initialValue={24}
                    style={{ marginBottom: 0 }}
                  >
                    <InputNumber min={0} max={720} addonAfter="小时" style={{ width: 160 }} />
                  </Form.Item>

                  <Form.Item
                    name="reviewTimeoutHours"
                    label="审核项时限"
                    initialValue={24}
                    style={{ marginBottom: 0 }}
                  >
                    <InputNumber min={0} max={720} addonAfter="小时" style={{ width: 160 }} />
                  </Form.Item>
                </Space>
              </Space>
            </Card>

            <Form.Item>
              <Space>
                <Button type="primary" htmlType="submit" loading={taskLoading}>
                  {isEdit ? '保存修改' : '创建任务'}
                </Button>
                <Button icon={<ArrowLeftOutlined />} onClick={() => navigate('/tasks')}>
                  返回列表
                </Button>
              </Space>
            </Form.Item>
          </Form>
        </Card>
      </Spin>
    </>
  );
}

// src/pages/TaskForm/index.vue
<template>
  <section class="task-form-page">
    <a-card class="page-hero" :body-style="{ padding: '18px 20px' }">
      <a-space direction="vertical" :size="4">
        <a-typography-title :level="4" class="page-title">
          {{ isEdit ? '编辑任务' : '创建任务' }}
        </a-typography-title>
        <a-typography-text type="secondary">
          配置任务基础信息、模板绑定和处理时效。
        </a-typography-text>
      </a-space>
    </a-card>

    <a-alert
      v-if="errorText"
      type="error"
      :message="errorText"
      show-icon
      closable
      @close="errorText = ''"
    />

    <a-spin :spinning="loading">
      <a-card class="form-card">
        <a-form
          ref="formRef"
          :model="formState"
          :rules="rules"
          layout="vertical"
          autocomplete="off"
          @finish="handleSubmit"
        >
          <a-form-item name="name" label="任务名称">
            <a-input
              v-model:value="formState.name"
              :maxlength="50"
              show-count
              placeholder="请输入任务名称"
            />
          </a-form-item>

          <a-form-item name="description" label="任务描述">
            <a-textarea
              v-model:value="formState.description"
              :maxlength="200"
              show-count
              :rows="3"
              placeholder="请输入任务描述"
            />
          </a-form-item>

          <a-form-item name="type" label="任务类型">
            <a-select
              v-model:value="formState.type"
              :options="taskTypeOptions"
              placeholder="请选择任务类型"
              @change="formState.templateId = undefined"
            />
          </a-form-item>

          <a-form-item name="owner" label="负责人">
            <a-select
              v-model:value="formState.owner"
              :options="ownerOptions"
              :loading="optionsLoading"
              placeholder="请选择负责人"
            />
          </a-form-item>

          <a-form-item name="templateId" label="绑定模板">
            <a-select
              v-model:value="formState.templateId"
              :options="templateOptions"
              :loading="templateStore.loading"
              :disabled="!formState.type"
              :placeholder="formState.type ? '请选择模板' : '请先选择任务类型'"
            />
          </a-form-item>

          <a-form-item name="instructions" label="任务说明">
            <a-textarea
              v-model:value="formState.instructions"
              :maxlength="500"
              show-count
              :rows="4"
              placeholder="请输入任务说明，如标注规范、注意事项等"
            />
          </a-form-item>

          <a-card size="small" title="任务时效" class="time-card">
            <a-row :gutter="[16, 12]">
              <a-col :xs="24" :md="12">
                <label class="field-label">任务开始</label>
                <input v-model="formState.startsAt" class="native-input" type="datetime-local" />
              </a-col>
              <a-col :xs="24" :md="12">
                <label class="field-label">任务期限</label>
                <input v-model="formState.dueAt" class="native-input" type="datetime-local" />
              </a-col>
              <a-col :xs="24" :md="12">
                <label class="field-label">标注项时限（小时）</label>
                <a-input-number
                  v-model:value="formState.annotationTimeoutHours"
                  :min="0"
                  :max="720"
                  class="full-control"
                />
              </a-col>
              <a-col :xs="24" :md="12">
                <label class="field-label">审核项时限（小时）</label>
                <a-input-number
                  v-model:value="formState.reviewTimeoutHours"
                  :min="0"
                  :max="720"
                  class="full-control"
                />
              </a-col>
            </a-row>
          </a-card>

          <a-form-item class="form-actions">
            <a-space>
              <a-button type="primary" html-type="submit" :loading="taskStore.loading">
                {{ isEdit ? '保存修改' : '创建任务' }}
              </a-button>
              <a-button @click="router.push('/tasks')">
                <template #icon><ArrowLeftOutlined /></template>
                返回列表
              </a-button>
            </a-space>
          </a-form-item>
        </a-form>
      </a-card>
    </a-spin>
  </section>
</template>

<script setup lang="ts">
import { computed, onMounted, reactive, ref, watch } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { message, type FormInstance, type FormProps } from 'ant-design-vue';
import { ArrowLeftOutlined } from '@ant-design/icons-vue';
import { AssignmentStrategy, TaskStatus, TaskType, type TaskItem } from '../../types';
import { getUserList } from '../../api/template';
import { useTaskStore } from '../../store/useTaskStore';
import { useTemplateStore } from '../../store/useTemplateStore';

const route = useRoute();
const router = useRouter();
const taskStore = useTaskStore();
const templateStore = useTemplateStore();
const formRef = ref<FormInstance>();

const optionsLoading = ref(false);
const errorText = ref('');
const ownerOptions = ref<Array<{ label: string; value: string }>>([]);

const editId = computed(() => (typeof route.query.id === 'string' ? route.query.id : ''));
const isEdit = computed(() => Boolean(editId.value));
const loading = computed(() => taskStore.loading || templateStore.loading || optionsLoading.value);
const editingTask = computed(() => taskStore.tasks.find((task) => task.id === editId.value));

const formState = reactive<{
  name: string;
  description: string;
  type: TaskType | undefined;
  owner: string | undefined;
  templateId: string | undefined;
  instructions: string;
  startsAt: string;
  dueAt: string;
  annotationTimeoutHours: number;
  reviewTimeoutHours: number;
}>({
  name: '',
  description: '',
  type: undefined,
  owner: undefined,
  templateId: undefined,
  instructions: '',
  startsAt: '',
  dueAt: '',
  annotationTimeoutHours: 24,
  reviewTimeoutHours: 24,
});

const rules: FormProps['rules'] = {
  name: [{ required: true, message: '请输入任务名称' }],
  description: [{ required: true, message: '请输入任务描述' }],
  type: [{ required: true, message: '请选择任务类型' }],
  owner: [{ required: true, message: '请选择负责人' }],
  templateId: [{ required: true, message: '请选择绑定模板' }],
  instructions: [{ required: true, message: '请输入任务说明' }],
};

const taskTypeOptions = [
  { label: '图像分类', value: TaskType.IMAGE_CLASSIFICATION },
  { label: '目标检测', value: TaskType.OBJECT_DETECTION },
  { label: '语义分割', value: TaskType.SEMANTIC_SEGMENTATION },
  { label: '文本 NER', value: TaskType.TEXT_NER },
];

const templateOptions = computed(() =>
  templateStore.templates
    .filter((template) => !formState.type || template.type === formState.type)
    .map((template) => ({ label: template.name, value: template.id })),
);

onMounted(async () => {
  await Promise.all([taskStore.fetchTasks(), templateStore.fetchTemplates(), loadOwners()]);
  fillFormFromTask();
});

watch(editingTask, () => fillFormFromTask());

async function loadOwners() {
  optionsLoading.value = true;
  try {
    const res = await getUserList();
    ownerOptions.value = (res.data.items || [])
      .filter((user) => user.role === 'owner' || user.role === 'admin')
      .map((user) => ({ label: user.username, value: user.username }));
  } catch (error) {
    errorText.value = error instanceof Error ? error.message : '加载负责人失败';
  } finally {
    optionsLoading.value = false;
  }
}

function fillFormFromTask() {
  const task = editingTask.value;
  if (!task) return;
  formState.name = task.name;
  formState.description = task.description;
  formState.type = task.type;
  formState.owner = task.owner;
  formState.templateId = task.templateId;
  formState.instructions = task.instructions;
  formState.startsAt = toLocalInputValue(task.startsAt);
  formState.dueAt = toLocalInputValue(task.dueAt);
  formState.annotationTimeoutHours = task.annotationTimeoutHours ?? 24;
  formState.reviewTimeoutHours = task.reviewTimeoutHours ?? 24;
}

async function handleSubmit() {
  await formRef.value?.validate();
  if (
    formState.startsAt &&
    formState.dueAt &&
    new Date(formState.dueAt) <= new Date(formState.startsAt)
  ) {
    message.warning('任务期限必须晚于任务开始');
    return;
  }

  const selectedTemplate = templateStore.templates.find(
    (template) => template.id === formState.templateId,
  );
  const payload: Partial<TaskItem> = {
    name: formState.name,
    description: formState.description,
    type: formState.type,
    owner: formState.owner,
    templateId: formState.templateId,
    templateName: selectedTemplate?.name ?? '',
    instructions: formState.instructions,
    startsAt: fromLocalInputValue(formState.startsAt),
    dueAt: fromLocalInputValue(formState.dueAt),
    annotationTimeoutHours: formState.annotationTimeoutHours,
    reviewTimeoutHours: formState.reviewTimeoutHours,
  };

  try {
    if (isEdit.value && editId.value) {
      await taskStore.updateTask(editId.value, payload);
      message.success('任务已更新');
    } else {
      await taskStore.addTask({
        ...payload,
        status: TaskStatus.DRAFT,
        assignmentConfig: { strategy: AssignmentStrategy.EVEN_SPLIT, annotators: [], options: {} },
        archived: false,
        archivedAt: null,
      } as Partial<TaskItem>);
      message.success('任务创建成功');
    }
    await router.push('/tasks');
  } catch (error) {
    errorText.value = error instanceof Error ? error.message : taskStore.error || '保存任务失败';
  }
}

function toLocalInputValue(value: string | null | undefined) {
  if (!value) return '';
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return '';
  const pad = (num: number) => String(num).padStart(2, '0');
  return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}T${pad(date.getHours())}:${pad(date.getMinutes())}`;
}

function fromLocalInputValue(value: string) {
  return value ? new Date(value).toISOString() : null;
}
</script>

<style scoped>
.task-form-page {
  display: flex;
  flex-direction: column;
  gap: 16px;
  min-width: 0;
}

.page-title {
  margin: 0;
}

.form-card {
  max-width: 860px;
}

.time-card {
  margin-bottom: 24px;
  background: #fff;
}

.field-label {
  display: block;
  margin-bottom: 6px;
  font-weight: 600;
}

.native-input {
  width: 100%;
  height: 32px;
  padding: 4px 11px;
  color: #202124;
  background: #fff;
  border: 1px solid var(--lh-border-strong);
  border-radius: 6px;
  outline: none;
  transition:
    border-color 0.15s ease,
    box-shadow 0.15s ease;
}

.native-input:focus {
  border-color: var(--lh-primary);
  box-shadow: 0 0 0 3px rgba(26, 115, 232, 0.14);
}

.full-control {
  width: 100%;
}

.form-actions {
  padding-top: 4px;
  margin-bottom: 0;
}
</style>
