// src/pages/NotificationPublish/index.tsx
import { useCallback, useEffect, useMemo, useState } from 'react';
import { Alert, Button, Card, Checkbox, Form, Input, message, Select, Space, Tag, Typography } from 'antd';
import { NotificationOutlined, SendOutlined } from '@ant-design/icons';
import { useLocation } from 'react-router-dom';
import { Role, type UserInfo } from '../../types';
import * as authApi from '../../api/auth';
import { publishNotification } from '../../api/notification';

const { Title, Text } = Typography;

const roleOptions = [
  { label: '负责人', value: Role.OWNER },
  { label: '标注员', value: Role.ANNOTATOR },
  { label: '审核员', value: Role.REVIEWER },
];

const priorityOptions = [
  { label: '普通', value: 'medium' },
  { label: '重要', value: 'high' },
  { label: '低优先级', value: 'low' },
];

interface PublishFormValues {
  title: string;
  message: string;
  priority: 'high' | 'medium' | 'low';
  targetRoles?: string[];
  targetUsernames?: string[];
}

export default function NotificationPublish() {
  const [form] = Form.useForm<PublishFormValues>();
  const location = useLocation();
  const [users, setUsers] = useState<UserInfo[]>([]);
  const [loadingUsers, setLoadingUsers] = useState(false);
  const [submitting, setSubmitting] = useState(false);

  const fetchUsers = useCallback(async () => {
    setLoadingUsers(true);
    try {
      const res = await authApi.getUserList();
      setUsers(res.data.items || []);
    } catch (err: any) {
      message.error(err?.message || '获取用户列表失败');
    } finally {
      setLoadingUsers(false);
    }
  }, []);

  useEffect(() => {
    fetchUsers();
  }, [fetchUsers]);

  useEffect(() => {
    const state = location.state as Partial<PublishFormValues> | null;
    if (!state) return;
    form.setFieldsValue({
      title: state.title,
      message: state.message,
      priority: state.priority || 'medium',
      targetRoles: state.targetRoles,
      targetUsernames: state.targetUsernames,
    });
  }, [form, location.state]);

  const userOptions = useMemo(
    () =>
      users.map((user) => ({
        label: `${user.username} (${roleOptions.find((role) => role.value === user.role)?.label || user.role})`,
        value: user.username,
      })),
    [users],
  );

  const handleSubmit = async () => {
    try {
      const values = await form.validateFields();
      const targetRoles = values.targetRoles || [];
      const targetUsernames = values.targetUsernames || [];

      if (targetRoles.length === 0 && targetUsernames.length === 0) {
        message.warning('请至少选择一个接收角色或接收人员');
        return;
      }

      setSubmitting(true);
      const res = await publishNotification({
        title: values.title,
        message: values.message,
        priority: values.priority,
        targetRoles,
        targetUsernames,
      });
      message.success(`通知已发布，送达 ${res.data.delivered} 人`);
      form.resetFields();
      form.setFieldsValue({ priority: 'medium' });
    } catch (err: any) {
      if (err?.message) message.error(err.message);
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 12, minHeight: 0 }}>
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
        <Space>
          <NotificationOutlined style={{ color: '#1677ff' }} />
          <Title level={4} style={{ margin: 0 }}>通知发布</Title>
        </Space>
        <Tag color="blue">负责人权限</Tag>
      </div>

      <Alert
        type="info"
        showIcon
        message="负责人发布的通知会进入接收人的通知铃铛，可按角色、人员或两者组合发送。"
      />

      <Card size="small" styles={{ body: { maxWidth: 760 } }}>
        <Form
          form={form}
          layout="vertical"
          initialValues={{ priority: 'medium' }}
          autoComplete="off"
        >
          <Form.Item
            name="title"
            label="通知标题"
            rules={[{ required: true, message: '请输入通知标题' }]}
          >
            <Input maxLength={60} showCount placeholder="例如：本周审核安排调整" />
          </Form.Item>

          <Form.Item
            name="message"
            label="通知内容"
            rules={[{ required: true, message: '请输入通知内容' }]}
          >
            <Input.TextArea rows={6} maxLength={500} showCount placeholder="请输入需要同步给目标人员的内容" />
          </Form.Item>

          <Form.Item name="priority" label="优先级">
            <Select style={{ width: 180 }} options={priorityOptions} />
          </Form.Item>

          <Form.Item name="targetRoles" label="按角色发送">
            <Checkbox.Group options={roleOptions} />
          </Form.Item>

          <Form.Item name="targetUsernames" label="按人员发送">
            <Select
              mode="multiple"
              allowClear
              showSearch
              optionFilterProp="label"
              loading={loadingUsers}
              options={userOptions}
              placeholder="选择指定接收人员"
            />
          </Form.Item>

          <Space>
            <Button type="primary" icon={<SendOutlined />} loading={submitting} onClick={handleSubmit}>
              发布通知
            </Button>
            <Button onClick={() => form.resetFields()}>重置</Button>
            <Text type="secondary">角色和人员取并集，重复人员只发送一次。</Text>
          </Space>
        </Form>
      </Card>
    </div>
  );
}

// src/pages/NotificationPublish/index.vue
<template>
  <section class="notification-page app-page">
    <header class="app-page-header">
      <div class="app-page-title">
        <a-typography-title :level="4" class="page-title">
          <NotificationOutlined class="page-icon" />
          通知发布
        </a-typography-title>
        <a-typography-text class="app-page-desc" type="secondary">
          按角色或指定人员发送站内通知。
        </a-typography-text>
      </div>
      <div class="app-page-tools">
        <a-tag color="blue">管理员权限</a-tag>
      </div>
    </header>

    <a-alert
      type="info"
      show-icon
      message="通知会进入接收人的通知中心，可按角色、指定人员或两者组合发送。"
    />

    <a-card size="small" class="form-card">
      <a-form ref="formRef" :model="formState" :rules="rules" layout="vertical" autocomplete="off">
        <a-form-item name="title" label="通知标题">
          <a-input
            v-model:value="formState.title"
            :maxlength="60"
            show-count
            placeholder="例如：本周审核安排调整"
          />
        </a-form-item>
        <a-form-item name="message" label="通知内容">
          <a-textarea
            v-model:value="formState.message"
            :rows="6"
            :maxlength="500"
            show-count
            placeholder="请输入需要同步给目标人员的内容"
          />
        </a-form-item>
        <a-form-item name="priority" label="优先级">
          <a-select
            v-model:value="formState.priority"
            class="priority-select"
            :options="priorityOptions"
          />
        </a-form-item>
        <a-form-item name="targetRoles" label="按角色发送">
          <a-checkbox-group v-model:value="formState.targetRoles" :options="roleOptions" />
        </a-form-item>
        <a-form-item name="targetUsernames" label="按人员发送">
          <a-select
            v-model:value="formState.targetUsernames"
            mode="multiple"
            allow-clear
            show-search
            option-filter-prop="label"
            :loading="loadingUsers"
            :options="userOptions"
            placeholder="选择指定接收人员"
          />
        </a-form-item>
        <a-space wrap class="form-actions">
          <a-button type="primary" :loading="submitting" @click="handleSubmit">
            <template #icon><SendOutlined /></template>
            发布通知
          </a-button>
          <a-button @click="resetForm">重置</a-button>
          <a-typography-text type="secondary">
            角色和人员取并集，重复人员只发送一次。
          </a-typography-text>
        </a-space>
      </a-form>
    </a-card>
  </section>
</template>

<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue';
import { useRoute } from 'vue-router';
import { message, type FormInstance, type FormProps } from 'ant-design-vue';
import { NotificationOutlined, SendOutlined } from '@ant-design/icons-vue';
import { publishNotification, type PublishNotificationParams } from '../../api/notification';
import * as authApi from '../../api/auth';
import { Role, type UserInfo } from '../../types';

type Priority = NonNullable<PublishNotificationParams['priority']>;

const route = useRoute();
const formRef = ref<FormInstance>();
const users = ref<UserInfo[]>([]);
const loadingUsers = ref(false);
const submitting = ref(false);

const formState = reactive({
  title: '',
  message: '',
  priority: 'medium' as Priority,
  targetRoles: [] as string[],
  targetUsernames: [] as string[],
});

const roleOptions = [
  { label: '负责人', value: Role.OWNER },
  { label: '标注员', value: Role.ANNOTATOR },
  { label: '审核员', value: Role.REVIEWER },
];

const priorityOptions = [
  { label: '普通', value: 'medium' },
  { label: '重要', value: 'high' },
  { label: '低优先级', value: 'low' },
];

const rules: FormProps['rules'] = {
  title: [{ required: true, message: '请输入通知标题' }],
  message: [{ required: true, message: '请输入通知内容' }],
};

const userOptions = computed(() =>
  users.value.map((user) => ({
    label: `${user.username} (${roleOptions.find((role) => role.value === user.role)?.label ?? user.role})`,
    value: user.username,
  })),
);

onMounted(() => {
  void fetchUsers();
  const query = route.query;
  if (typeof query.title === 'string') formState.title = query.title;
  if (typeof query.message === 'string') formState.message = query.message;
});

async function fetchUsers() {
  loadingUsers.value = true;
  try {
    const res = await authApi.getUserList();
    users.value = res.data.items || [];
  } catch (error) {
    message.error(error instanceof Error ? error.message : '获取用户列表失败');
  } finally {
    loadingUsers.value = false;
  }
}

async function handleSubmit() {
  await formRef.value?.validate();
  if (formState.targetRoles.length === 0 && formState.targetUsernames.length === 0) {
    message.warning('请至少选择一个接收角色或接收人员');
    return;
  }

  submitting.value = true;
  try {
    const res = await publishNotification({
      title: formState.title,
      message: formState.message,
      priority: formState.priority,
      targetRoles: formState.targetRoles,
      targetUsernames: formState.targetUsernames,
    });
    message.success(`通知已发布，送达 ${res.data.delivered} 人`);
    resetForm();
  } catch (error) {
    message.error(error instanceof Error ? error.message : '发布通知失败');
  } finally {
    submitting.value = false;
  }
}

function resetForm() {
  formRef.value?.resetFields();
  formState.priority = 'medium';
  formState.targetRoles = [];
  formState.targetUsernames = [];
}
</script>

<style scoped>
.page-title {
  display: flex;
  align-items: center;
  gap: 8px;
  margin: 0;
}

.page-icon {
  color: var(--lh-primary);
}

.form-card {
  max-width: 820px;
}

.priority-select {
  width: 180px;
}

.form-actions {
  align-items: center;
}
</style>
