// src/pages/DataExport/index.tsx
﻿import { useState, useMemo, useCallback, useEffect } from 'react';
import {
  Typography,
  Card,
  Select,
  Radio,
  Button,
  Table,
  Space,
  Tag,
  Statistic,
  Row,
  Col,
  Alert,
  Empty,
  message,
  Tooltip,
} from 'antd';
import {
  DownloadOutlined,
  FileTextOutlined,
  FileExcelOutlined,
  InfoCircleOutlined,
} from '@ant-design/icons';
import type { ColumnsType } from 'antd/es/table';
import { DataItemStatus, STATUS_DISPLAY_CONFIG } from '../../types';
import { useTaskStore } from '../../store/useTaskStore';
import { useAnnotationStore } from '../../store/useAnnotationStore';
import {
  ExportFormat,
  ExportRange,
  type ExportRecord,
  buildExportRecords,
  filterByRange,
  performExport,
  CSV_COLUMN_MAP,
  CSV_COLUMN_ORDER,
} from '../../utils/exportUtils';

const { Title, Paragraph } = Typography;

const RANGE_OPTIONS = [
  { label: '全部数据', value: ExportRange.ALL },
  { label: '仅审核通过', value: ExportRange.APPROVED },
  { label: '仅驳回数据', value: ExportRange.REJECTED },
];

const FORMAT_OPTIONS = [
  { label: 'JSON', value: ExportFormat.JSON },
  { label: 'CSV', value: ExportFormat.CSV },
];

function renderStatusTag(status: DataItemStatus) {
  const config = STATUS_DISPLAY_CONFIG[status];
  return <Tag color={config.color}>{config.label}</Tag>;
}

export default function DataExport() {
  const tasks = useTaskStore((s) => s.tasks);
  const fetchTasks = useTaskStore((s) => s.fetchTasks);
  const dataItems = useAnnotationStore((s) => s.dataItems);
  const archivedItems = useAnnotationStore((s) => s.archivedItems);
  const aiReviewResults = useAnnotationStore((s) => s.aiReviewResults);
  const fetchDataItems = useAnnotationStore((s) => s.fetchDataItems);
  const fetchArchivedItems = useAnnotationStore((s) => s.fetchArchivedItems);
  const fetchAIReviews = useAnnotationStore((s) => s.fetchAIReviews);

  // 页面加载时从 API 获取数据
  useEffect(() => {
    fetchTasks();
    fetchDataItems();
    fetchArchivedItems();
    fetchAIReviews();
  }, [fetchTasks, fetchDataItems, fetchArchivedItems, fetchAIReviews]);

  const [selectedTaskId, setSelectedTaskId] = useState<string | undefined>(undefined);
  const [exportRange, setExportRange] = useState<ExportRange>(ExportRange.ALL);
  const [exportFormat, setExportFormat] = useState<ExportFormat>(ExportFormat.JSON);

  const taskOptions = useMemo(
    () =>
      tasks.map((t) => ({
        label: t.name + '（' + t.id + '）',
        value: t.id,
      })),
    [tasks],
  );

  const allExportRecords = useMemo(() => {
    const itemMap = new Map(dataItems.map((item) => [item.id, item]));
    archivedItems.forEach((item) => itemMap.set(item.id, item));
    const exportItems = Array.from(itemMap.values());
    const filteredItems = selectedTaskId
      ? exportItems.filter((d) => d.taskId === selectedTaskId)
      : exportItems;
    return buildExportRecords(filteredItems, aiReviewResults);
  }, [selectedTaskId, dataItems, archivedItems, aiReviewResults]);

  const exportRecords = useMemo(
    () => filterByRange(allExportRecords, exportRange),
    [allExportRecords, exportRange],
  );

  const stats = useMemo(() => {
    const total = allExportRecords.length;
    const approved = allExportRecords.filter((r) => r.status === DataItemStatus.REVIEWED).length;
    const rejected = allExportRecords.filter((r) => r.status === DataItemStatus.REJECTED).length;
    return { total, approved, rejected };
  }, [allExportRecords]);

  const selectedTaskName = useMemo(() => {
    if (!selectedTaskId) return 'LabelHub_全部任务';
    const task = tasks.find((t) => t.id === selectedTaskId);
    return task ? 'LabelHub_' + task.name : 'LabelHub_导出';
  }, [selectedTaskId, tasks]);

  const handleExport = useCallback(() => {
    if (exportRecords.length === 0) {
      message.warning('没有可导出的数据');
      return;
    }
    performExport(exportRecords, exportFormat, selectedTaskName);
    message.success('已导出 ' + exportRecords.length + ' 条数据');
  }, [exportRecords, exportFormat, selectedTaskName]);

  const previewColumns: ColumnsType<ExportRecord> = useMemo(
    () => [
      {
        title: '数据ID',
        dataIndex: 'id',
        key: 'id',
        width: 80,
      },
      {
        title: '任务ID',
        dataIndex: 'taskId',
        key: 'taskId',
        width: 80,
      },
      {
        title: '状态',
        dataIndex: 'status',
        key: 'status',
        width: 110,
        render: (status: DataItemStatus) => renderStatusTag(status),
      },
      {
        title: '原始数据',
        dataIndex: 'rawData',
        key: 'rawData',
        width: 200,
        ellipsis: true,
        render: (v: Record<string, unknown> | null) =>
          v ? (
            <Tooltip title={JSON.stringify(v, null, 2)}>
              <span style={{ cursor: 'pointer' }}>{JSON.stringify(v).slice(0, 60) + '…'}</span>
            </Tooltip>
          ) : (
            <Tag>无</Tag>
          ),
      },
      {
        title: '标注结果',
        dataIndex: 'annotationResult',
        key: 'annotationResult',
        width: 200,
        ellipsis: true,
        render: (v: Record<string, unknown> | null) =>
          v ? (
            <Tooltip title={JSON.stringify(v, null, 2)}>
              <span style={{ cursor: 'pointer' }}>{JSON.stringify(v).slice(0, 60) + '…'}</span>
            </Tooltip>
          ) : (
            <Tag>未标注</Tag>
          ),
      },
      {
        title: 'AI预审',
        key: 'aiReview',
        width: 130,
        render: (_: unknown, record: ExportRecord) => {
          const ai = record.aiReviewResult;
          if (!ai) return <Tag>无</Tag>;
          const colorMap: Record<string, string> = {
            pass: 'success',
            risk: 'warning',
            fail: 'error',
          };
          return (
            <Space direction="vertical" size={0}>
              <Tag color={colorMap[ai.reviewStatus] ?? 'default'}>{ai.reviewStatus}</Tag>
              <span style={{ fontSize: 12, color: '#999' }}>评分: {ai.score}</span>
            </Space>
          );
        },
      },
      {
        title: '人工审核',
        key: 'humanReview',
        width: 150,
        render: (_: unknown, record: ExportRecord) => {
          const human = record.humanReviewResult;
          if (!human || !human.result) return <Tag>无</Tag>;
          const colorMap: Record<string, string> = {
            approved: 'success',
            rejected: 'error',
          };
          const labelMap: Record<string, string> = {
            approved: '通过',
            rejected: '驳回',
          };
          return (
            <Space direction="vertical" size={0}>
              <Tag color={colorMap[human.result]}>{labelMap[human.result]}</Tag>
              {human.reviewer && (
                <span style={{ fontSize: 12, color: '#999' }}>审核人: {human.reviewer}</span>
              )}
              {human.rejectReason && (
                <Tooltip title={human.rejectReason}>
                  <span style={{ fontSize: 12, color: '#ff4d4f', cursor: 'pointer' }}>
                    驳回原因…
                  </span>
                </Tooltip>
              )}
            </Space>
          );
        },
      },
    ],
    [],
  );

  return (
    <>
      <Title level={4}>数据导出</Title>
      <Paragraph type="secondary">
        选择任务与导出条件，预览后点击导出按钮下载标注数据。
      </Paragraph>

      <Card title="导出配置" size="small" style={{ marginBottom: 16 }}>
        <Row gutter={[24, 16]} align="middle">
          <Col xs={24} md={8}>
            <div style={{ marginBottom: 4, fontWeight: 500 }}>
              <InfoCircleOutlined style={{ marginRight: 4 }} />
              选择任务
            </div>
            <Select
              placeholder="选择要导出的任务（留空=全部）"
              allowClear
              showSearch
              style={{ width: '100%' }}
              options={taskOptions}
              value={selectedTaskId}
              onChange={(val) => setSelectedTaskId(val)}
              filterOption={(input, option) =>
                (option?.label as string)?.toLowerCase().includes(input.toLowerCase())
              }
            />
          </Col>

          <Col xs={24} md={8}>
            <div style={{ marginBottom: 4, fontWeight: 500 }}>导出范围</div>
            <Radio.Group
              options={RANGE_OPTIONS}
              value={exportRange}
              onChange={(e) => setExportRange(e.target.value)}
              optionType="button"
              buttonStyle="solid"
            />
          </Col>

          <Col xs={24} md={8}>
            <div style={{ marginBottom: 4, fontWeight: 500 }}>导出格式</div>
            <Radio.Group
              options={FORMAT_OPTIONS}
              value={exportFormat}
              onChange={(e) => setExportFormat(e.target.value)}
              optionType="button"
              buttonStyle="solid"
            />
          </Col>
        </Row>
      </Card>

      <Card title="数据概览" size="small" style={{ marginBottom: 16 }}>
        <Row gutter={16} align="middle">
          <Col span={6}>
            <Statistic title="总数据" value={stats.total} />
          </Col>
          <Col span={6}>
            <Statistic
              title="审核通过"
              value={stats.approved}
              valueStyle={{ color: '#52c41a' }}
            />
          </Col>
          <Col span={6}>
            <Statistic
              title="已驳回"
              value={stats.rejected}
              valueStyle={{ color: '#ff4d4f' }}
            />
          </Col>
          <Col span={6} style={{ textAlign: 'right' }}>
            <Space>
              <span style={{ color: '#999' }}>
                当前筛选: <strong>{exportRecords.length}</strong> 条
              </span>
              <Button
                type="primary"
                size="large"
                icon={
                  exportFormat === ExportFormat.JSON ? (
                    <FileTextOutlined />
                  ) : (
                    <FileExcelOutlined />
                  )
                }
                onClick={handleExport}
                disabled={exportRecords.length === 0}
              >
                {'导出 ' + exportFormat.toUpperCase()}
              </Button>
            </Space>
          </Col>
        </Row>
      </Card>

      <Card
        title="导出字段映射"
        size="small"
        style={{ marginBottom: 16 }}
        extra={<DownloadOutlined />}
      >
        <Alert
          type="info"
          showIcon
          message="导出字段说明"
          description={
            <div>
              <p style={{ marginBottom: 8 }}>
                导出文件包含以下字段，其中嵌套对象在 CSV 中以 JSON
                序列化形式存储，同时将常用字段提取为独立列便于筛选：
              </p>
              <Row gutter={[8, 4]}>
                {CSV_COLUMN_ORDER.map((key) => (
                  <Col key={key} span={8}>
                    <Tag style={{ margin: 0 }}>
                      {CSV_COLUMN_MAP[key] + '（' + key + '）'}
                    </Tag>
                  </Col>
                ))}
              </Row>
            </div>
          }
          style={{ marginBottom: 0 }}
        />
      </Card>

      <Card
        title={'数据预览（' + exportRecords.length + ' 条）'}
        size="small"
        extra={
          <span style={{ color: '#999', fontSize: 12 }}>
            仅展示摘要，完整数据请下载导出文件
          </span>
        }
      >
        {exportRecords.length === 0 ? (
          <Empty
            description={
              selectedTaskId
                ? '所选任务下没有符合条件的数据'
                : '没有符合条件的数据，请调整筛选范围'
            }
          />
        ) : (
          <Table<ExportRecord>
            rowKey="id"
            columns={previewColumns}
            dataSource={exportRecords}
            size="small"
            pagination={{
              pageSize: 10,
              showSizeChanger: false,
              showTotal: (total) => '共 ' + total + ' 条',
            }}
            scroll={{ x: 950 }}
          />
        )}
      </Card>
    </>
  );
}

// src/pages/DataExport/index.vue
<template>
  <section class="data-export-page app-page">
    <header class="app-page-header">
      <div class="app-page-title">
        <a-typography-title :level="4" class="page-title">数据导出</a-typography-title>
        <a-typography-text class="app-page-desc" type="secondary">选择任务、范围和格式后导出标注数据。</a-typography-text>
      </div>
      <div class="app-page-tools">
        <a-tag color="blue">总数据 {{ stats.total }}</a-tag>
        <a-tag color="green">通过 {{ stats.approved }}</a-tag>
        <a-tag color="red">驳回 {{ stats.rejected }}</a-tag>
      </div>
    </header>

    <a-card title="导出配置" class="panel-card export-config-card">
      <a-row :gutter="[16, 16]" align="middle">
        <a-col :xs="24" :md="8">
          <div class="field-label">选择任务</div>
          <a-select
            v-model:value="selectedTaskId"
            allow-clear
            show-search
            option-filter-prop="label"
            placeholder="留空导出全部任务"
            class="full-control"
            :options="taskOptions"
          />
        </a-col>
        <a-col :xs="24" :md="8">
          <div class="field-label">导出范围</div>
          <a-radio-group v-model:value="exportRange" option-type="button" button-style="solid" :options="rangeOptions" class="segmented-group" />
        </a-col>
        <a-col :xs="24" :md="8">
          <div class="field-label">导出格式</div>
          <a-radio-group v-model:value="exportFormat" option-type="button" button-style="solid" :options="formatOptions" class="segmented-group" />
        </a-col>
      </a-row>
    </a-card>

    <a-row :gutter="[16, 16]">
      <a-col :xs="24" :md="6">
        <a-card class="metric-card metric-card--blue"><a-statistic title="总数据" :value="stats.total" /></a-card>
      </a-col>
      <a-col :xs="24" :md="6">
        <a-card class="metric-card metric-card--green"><a-statistic title="审核通过" :value="stats.approved" /></a-card>
      </a-col>
      <a-col :xs="24" :md="6">
        <a-card class="metric-card metric-card--red"><a-statistic title="已驳回" :value="stats.rejected" /></a-card>
      </a-col>
      <a-col :xs="24" :md="6">
        <a-card class="export-card">
          <a-button type="primary" block :disabled="exportRecords.length === 0" @click="handleExport">
            <template #icon><DownloadOutlined /></template>
            导出 {{ exportFormat.toUpperCase() }}
          </a-button>
        </a-card>
      </a-col>
    </a-row>

    <a-card class="app-table-card" :body-style="{ padding: 0 }">
      <template #title>
        <a-space>
          <span>数据预览</span>
          <a-tag color="blue">{{ exportRecords.length }} 条</a-tag>
        </a-space>
      </template>
      <a-empty v-if="exportRecords.length === 0" description="暂无符合条件的数据" />
      <a-table
        v-else
        row-key="id"
        size="small"
        :columns="columns"
        :data-source="exportRecords"
        :pagination="{ pageSize: 10, showSizeChanger: false }"
      >
        <template #bodyCell="{ column, record }">
          <template v-if="column.key === 'status'">
            <a-tag :color="getDataStatusMeta(record.status).color">{{ getDataStatusMeta(record.status).label }}</a-tag>
          </template>
          <template v-else-if="column.key === 'rawData'">
            <a-tooltip :title="stringify(record.rawData)">
              <span class="preview-text">{{ stringify(record.rawData) }}</span>
            </a-tooltip>
          </template>
          <template v-else-if="column.key === 'annotationResult'">
            <a-tooltip :title="stringify(record.annotationResult)">
              <span class="preview-text">{{ stringify(record.annotationResult) }}</span>
            </a-tooltip>
          </template>
          <template v-else-if="column.key === 'aiReview'">
            <a-tag v-if="record.aiReviewResult">{{ record.aiReviewResult.reviewStatus }}</a-tag>
            <a-tag v-else>无</a-tag>
          </template>
          <template v-else-if="column.key === 'humanReview'">
            <a-tag v-if="record.humanReviewResult?.result" :color="record.humanReviewResult.result === 'approved' ? 'success' : 'error'">
              {{ record.humanReviewResult.result === 'approved' ? '通过' : '驳回' }}
            </a-tag>
            <a-tag v-else>无</a-tag>
          </template>
        </template>
      </a-table>
    </a-card>
  </section>
</template>

<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';
import { message, type TableColumnsType } from 'ant-design-vue';
import { DownloadOutlined } from '@ant-design/icons-vue';
import { DataItemStatus, STATUS_DISPLAY_CONFIG, type DataItem } from '../../types';
import { useAnnotationStore } from '../../store/useAnnotationStore';
import { useTaskStore } from '../../store/useTaskStore';
import {
  ExportFormat,
  ExportRange,
  buildExportRecords,
  filterByRange,
  performExport,
  type ExportRecord,
} from '../../utils/exportUtils';

const taskStore = useTaskStore();
const annotationStore = useAnnotationStore();

const selectedTaskId = ref<string | undefined>();
const exportRange = ref<ExportRange>(ExportRange.ALL);
const exportFormat = ref<ExportFormat>(ExportFormat.JSON);

const rangeOptions = [
  { label: '全部数据', value: ExportRange.ALL },
  { label: '仅审核通过', value: ExportRange.APPROVED },
  { label: '仅驳回数据', value: ExportRange.REJECTED },
];

const formatOptions = [
  { label: 'JSON', value: ExportFormat.JSON },
  { label: 'CSV', value: ExportFormat.CSV },
];

const columns: TableColumnsType<ExportRecord> = [
  { title: '数据ID', dataIndex: 'id', key: 'id', width: 112, ellipsis: true },
  { title: '任务ID', dataIndex: 'taskId', key: 'taskId', width: 112, ellipsis: true, responsive: ['xl'] },
  { title: '状态', dataIndex: 'status', key: 'status', width: 96 },
  { title: '原始数据', dataIndex: 'rawData', key: 'rawData', ellipsis: true },
  { title: '标注结果', dataIndex: 'annotationResult', key: 'annotationResult', ellipsis: true },
  { title: 'AI', key: 'aiReview', width: 84, responsive: ['lg'] },
  { title: '审核', key: 'humanReview', width: 84 },
];

const taskOptions = computed(() =>
  taskStore.tasks.map((task) => ({
    label: `${task.name} (${task.id})`,
    value: task.id,
  })),
);

const allExportRecords = computed(() => {
  const itemMap = new Map<string, DataItem>();
  annotationStore.dataItems.forEach((item) => itemMap.set(item.id, item));
  annotationStore.archivedItems.forEach((item) => itemMap.set(item.id, item));

  const items = Array.from(itemMap.values()).filter((item) => !selectedTaskId.value || item.taskId === selectedTaskId.value);
  return buildExportRecords(items, annotationStore.aiReviewResults);
});

const exportRecords = computed(() => filterByRange(allExportRecords.value, exportRange.value));

const stats = computed(() => ({
  total: allExportRecords.value.length,
  approved: allExportRecords.value.filter((record) => record.status === DataItemStatus.REVIEWED).length,
  rejected: allExportRecords.value.filter((record) => record.status === DataItemStatus.REJECTED).length,
}));

onMounted(() => {
  void taskStore.fetchTasks();
  void annotationStore.fetchDataItems();
  void annotationStore.fetchArchivedItems();
  void annotationStore.fetchAIReviews();
});

function handleExport() {
  if (exportRecords.value.length === 0) {
    message.warning('没有可导出的数据');
    return;
  }

  const task = taskStore.tasks.find((item) => item.id === selectedTaskId.value);
  const baseFilename = task ? `LabelHub_${task.name}` : 'LabelHub_全部任务';
  performExport(exportRecords.value, exportFormat.value, baseFilename);
  message.success(`已导出 ${exportRecords.value.length} 条数据`);
}

function stringify(value: unknown) {
  if (value === null || value === undefined) return '无';
  return typeof value === 'string' ? value : JSON.stringify(value);
}

function getDataStatusMeta(status: DataItemStatus) {
  return STATUS_DISPLAY_CONFIG[status] ?? { label: status, color: 'default' };
}
</script>

<style scoped>
.panel-card,
.metric-card,
.export-card,
.app-table-card {
  height: 100%;
  box-shadow: none;
}

.export-card :deep(.ant-card-body) {
  display: flex;
  align-items: center;
  height: 100%;
}

.export-config-card :deep(.ant-card-body) {
  padding: 18px;
}

.field-label {
  margin-bottom: 6px;
  font-weight: 600;
}

.full-control {
  width: 100%;
}

.segmented-group {
  display: flex;
  flex-wrap: wrap;
  gap: 0;
}

.preview-text {
  display: inline-block;
  max-width: 190px;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  vertical-align: bottom;
}
@media (max-width: 576px) {
  .segmented-group,
  .segmented-group :deep(.ant-radio-button-wrapper) {
    width: 100%;
  }

  .segmented-group :deep(.ant-radio-button-wrapper) {
    text-align: center;
  }
}
</style>
